development:
  :address: smtp.gmail.com
  :port: 465
  :authentication: login
  :domain: gmail.com
  :user_name: testmailercontactv17
  :password: Testmail@1
  :tls: true
  :ssl: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: xxx
  :password: yyy
  :enable_starttls_auto: true
